import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getDatabase } from "firebase/database";
import { create } from 'zustand';
import { User, Transaction, Category, Budget, SavingsGoal, Settings, Notification } from '../types';
import { DEFAULT_CATEGORIES } from '../constants';
import { get, onValue, push, ref, remove, set, update } from 'firebase/database';
import { signInWithPopup, GoogleAuthProvider, signOut, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, updateProfile, sendPasswordResetEmail } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyDS5LOiWrZ7DudQ9ajfwGhqvjPBuzGpMNA",
  authDomain: "fintrack-21efc.firebaseapp.com",
  databaseURL: "https://fintrack-21efc-default-rtdb.firebaseio.com",
  projectId: "fintrack-21efc",
  storageBucket: "fintrack-21efc.firebasestorage.app",
  messagingSenderId: "156086710178",
  appId: "1:156086710178:web:926ff0627d446e093d0cfb"
};

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getDatabase(app);

type FinTrackStore = { user: User | null; transactions: Transaction[]; categories: Category[]; budgets: Budget[]; goals: SavingsGoal[]; settings: Settings | null; notifications: Notification[]; isLoading: boolean; error: string | null; init: () => void; login: (email: string, password: string) => Promise<boolean>; signup: (name: string, email: string, password: string) => Promise<boolean>; googleLogin: () => Promise<boolean>; resetPassword: (email: string) => Promise<boolean>; logout: () => void; updateUserProfile: (updates: Partial<User>) => Promise<void>; addTransaction: (txn: Omit<Transaction, 'id' | 'userId'>) => Promise<void>; updateTransaction: (txn: Transaction) => Promise<void>; deleteTransaction: (id: string) => Promise<void>; addCategory: (category: Omit<Category, 'id' | 'userId'>) => Promise<void>; updateCategory: (category: Category) => Promise<void>; deleteCategory: (id: string) => Promise<void>; saveBudget: (budget: Omit<Budget, 'id' | 'userId'>) => Promise<void>; deleteBudget: (id: string) => Promise<void>; saveGoal: (goal: Omit<SavingsGoal, 'id' | 'userId'> | SavingsGoal) => Promise<void>; deleteGoal: (id: string) => Promise<void>; updateSettings: (settings: Settings) => Promise<void>; addNotification: (title: string, message: string, type: Notification['type']) => Promise<void>; markNotificationRead: (id: string) => Promise<void>; markAllNotificationsRead: () => Promise<void>; clearNotifications: () => Promise<void>; resetAllData: () => void };
const userPath = (uid: string, child = '') => `users/${uid}${child ? `/${child}` : ''}`;
const valuesAt = <T,>(value: unknown): T[] => value && typeof value === 'object' ? Object.entries(value as Record<string, T>).map(([id, item]) => ({ ...item, id })) : [];
let databaseUnsubscribers: (() => void)[] = [];

export const useStore = create<FinTrackStore>((setState, getState) => ({
  user: null, transactions: [], categories: [], budgets: [], goals: [], settings: null, notifications: [], isLoading: true, error: null,
  init: () => { onAuthStateChanged(auth, async (firebaseUser) => { databaseUnsubscribers.forEach((unsubscribe) => unsubscribe()); databaseUnsubscribers = []; if (!firebaseUser) { setState({ user: null, transactions: [], categories: [], budgets: [], goals: [], settings: null, notifications: [], isLoading: false }); return; } try { const root = ref(db, userPath(firebaseUser.uid)); const snapshot = await get(root); let user: User; if (snapshot.exists() && snapshot.val().id) user = snapshot.val() as User; else { user = { id: firebaseUser.uid, name: firebaseUser.displayName || 'User', email: firebaseUser.email || '', currency: 'INR', theme: 'light', createdAt: new Date().toISOString() }; await set(root, user); const categories: Record<string, Category> = {}; DEFAULT_CATEGORIES.forEach((category) => { categories[category.id] = { ...category, userId: firebaseUser.uid }; }); await set(ref(db, userPath(firebaseUser.uid, 'categories')), categories); await set(ref(db, userPath(firebaseUser.uid, 'settings')), { darkMode: false, currency: 'INR', backupReminder: true, largeExpenseThreshold: 50000 }); } setState({ user, isLoading: false, error: null }); const listen = (child: string, callback: (value: unknown) => void) => { databaseUnsubscribers.push(onValue(ref(db, userPath(firebaseUser.uid, child)), (value) => callback(value.val()))); }; listen('settings', (value) => setState({ settings: value as Settings | null })); listen('transactions', (value) => setState({ transactions: valuesAt<Transaction>(value).sort((a, b) => b.date.localeCompare(a.date)) })); listen('categories', (value) => setState({ categories: valuesAt<Category>(value) })); listen('budgets', (value) => setState({ budgets: valuesAt<Budget>(value) })); listen('goals', (value) => setState({ goals: valuesAt<SavingsGoal>(value) })); listen('notifications', (value) => setState({ notifications: valuesAt<Notification>(value).sort((a, b) => b.date.localeCompare(a.date)) })); } catch (error) { setState({ isLoading: false, error: error instanceof Error ? error.message : 'Failed to load user data' }); } }); },
  login: async (email, password) => { setState({ isLoading: true, error: null }); try { await signInWithEmailAndPassword(auth, email, password); return true; } catch (error) { setState({ isLoading: false, error: error instanceof Error ? error.message : 'Failed to login' }); return false; } }, signup: async (name, email, password) => { setState({ isLoading: true, error: null }); try { const credential = await createUserWithEmailAndPassword(auth, email, password); await updateProfile(credential.user, { displayName: name }); return true; } catch (error) { setState({ isLoading: false, error: error instanceof Error ? error.message : 'Failed to sign up' }); return false; } }, googleLogin: async () => { setState({ isLoading: true, error: null }); try { await signInWithPopup(auth, new GoogleAuthProvider()); return true; } catch (error) { setState({ isLoading: false, error: error instanceof Error ? error.message : 'Google sign in failed' }); return false; } }, resetPassword: async (email) => { try { await sendPasswordResetEmail(auth, email); return true; } catch (error) { setState({ error: error instanceof Error ? error.message : 'Failed to send password reset email' }); return false; } }, logout: async () => { await signOut(auth); },
  updateUserProfile: async (updates) => { const { user } = getState(); if (!user) return; await update(ref(db, userPath(user.id)), updates); if (updates.name && auth.currentUser) await updateProfile(auth.currentUser, { displayName: updates.name }); setState({ user: { ...user, ...updates } }); },
  addTransaction: async (txn) => { const { user, settings } = getState(); if (!user) throw new Error('You must be signed in before adding a transaction.'); try { const item = push(ref(db, userPath(user.id, 'transactions'))); const transaction = Object.fromEntries(Object.entries({ ...txn, id: item.key, userId: user.id }).filter(([, value]) => value !== undefined)); await set(item, transaction); if (settings && txn.type === 'expense' && txn.amount >= settings.largeExpenseThreshold) await getState().addNotification('Large Expense Added', `A large expense of ${settings.currency} ${txn.amount.toLocaleString()} for "${txn.title}" was recorded.`, 'large_expense'); } catch (error) { setState({ error: error instanceof Error ? error.message : 'Failed to save transaction' }); throw error; } },
  updateTransaction: async (txn) => { const { user } = getState(); if (user) { const transaction = Object.fromEntries(Object.entries(txn).filter(([, value]) => value !== undefined)); await update(ref(db, userPath(user.id, `transactions/${txn.id}`)), transaction); } }, deleteTransaction: async (id) => { const { user } = getState(); if (user) await remove(ref(db, userPath(user.id, `transactions/${id}`))); },
  addCategory: async (category) => { const { user } = getState(); if (user) { const item = push(ref(db, userPath(user.id, 'categories'))); await set(item, { ...category, id: item.key, userId: user.id }); } }, updateCategory: async (category) => { const { user } = getState(); if (user) await update(ref(db, userPath(user.id, `categories/${category.id}`)), category); }, deleteCategory: async (id) => { const { user } = getState(); if (user) await remove(ref(db, userPath(user.id, `categories/${id}`))); },
  saveBudget: async (budget) => { const { user } = getState(); if (user) { const id = 'id' in budget && budget.id ? budget.id : push(ref(db, userPath(user.id, 'budgets'))).key; if (id) await set(ref(db, userPath(user.id, `budgets/${id}`)), { ...budget, id, userId: user.id }); } }, deleteBudget: async (id) => { const { user } = getState(); if (user) await remove(ref(db, userPath(user.id, `budgets/${id}`))); }, saveGoal: async (goal) => { const { user } = getState(); if (user) { const id = 'id' in goal && goal.id ? goal.id : push(ref(db, userPath(user.id, 'goals'))).key; if (id) await set(ref(db, userPath(user.id, `goals/${id}`)), { ...goal, id, userId: user.id }); } }, deleteGoal: async (id) => { const { user } = getState(); if (user) await remove(ref(db, userPath(user.id, `goals/${id}`))); },
  updateSettings: async (settings) => { const { user } = getState(); if (user) { await set(ref(db, userPath(user.id, 'settings')), settings); await getState().updateUserProfile({ theme: settings.darkMode ? 'dark' : 'light' }); } }, addNotification: async (title, message, type) => { const { user } = getState(); if (user) { const item = push(ref(db, userPath(user.id, 'notifications'))); await set(item, { id: item.key, userId: user.id, title, message, type, date: new Date().toISOString(), read: false }); } }, markNotificationRead: async (id) => { const { user } = getState(); if (user) await update(ref(db, userPath(user.id, `notifications/${id}`)), { read: true }); }, markAllNotificationsRead: async () => { const { user, notifications } = getState(); if (user) { const changes: Record<string, boolean> = {}; notifications.filter((item) => !item.read).forEach((item) => { changes[`notifications/${item.id}/read`] = true; }); if (Object.keys(changes).length) await update(ref(db, userPath(user.id)), changes); } }, clearNotifications: async () => { const { user } = getState(); if (user) await remove(ref(db, userPath(user.id, 'notifications'))); }, resetAllData: () => { signOut(auth); },
}));
